sonar.projectKey=Danush1104_Working_ecom
sonar.organization=danush1104

# The directories to analyze
sonar.sources=frontend/src,product-service/app,inventory-service/app,order-service/app,cart-service/app,payment-service/app

# Exclude everything from coverage since we do not have unit tests yet
sonar.coverage.exclusions=**/*

# Exclude lambda_handler.py from duplication checks since they share a standard template
sonar.cpd.exclusions=**/lambda_handler.py
