sonar.projectKey=Danush1104_Working_ecom
sonar.organization=danush1104

# The directories to analyze
sonar.sources=frontend/src,product-service/app,inventory-service/app,order-service/app,cart-service/app,payment-service/app
