# Service Constants

# Error Codes
ERROR_PRODUCT_ALREADY_EXISTS = "PRODUCT_ALREADY_EXISTS"
ERROR_PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
ERROR_INVALID_PRICE = "INVALID_PRICE"
ERROR_INVALID_CATEGORY = "INVALID_CATEGORY"
ERROR_INVALID_PRODUCT_NAME = "INVALID_PRODUCT_NAME"
ERROR_INVALID_REQUEST = "INVALID_REQUEST"
ERROR_DATABASE_ERROR = "DATABASE_ERROR"
ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERROR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

# General
DEFAULT_CHARSET = "utf-8"
