# Service Constants

# Error Codes
ERROR_PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
ERROR_INVENTORY_NOT_FOUND = "INVENTORY_NOT_FOUND"
ERROR_INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
ERROR_INVALID_STOCK = "INVALID_STOCK"
ERROR_INVALID_QUANTITY = "INVALID_QUANTITY"
ERROR_RESERVATION_FAILED = "RESERVATION_FAILED"
ERROR_RELEASE_FAILED = "RELEASE_FAILED"
ERROR_DEDUCTION_FAILED = "DEDUCTION_FAILED"
ERROR_RESTORE_FAILED = "RESTORE_FAILED"
ERROR_DATABASE_ERROR = "DATABASE_ERROR"
ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERROR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
ERROR_PRODUCT_SERVICE_ERROR = "PRODUCT_SERVICE_ERROR"
ERROR_DUPLICATE_EVENT = "DUPLICATE_EVENT"

# General
DEFAULT_CHARSET = "utf-8"
