# Service Constants

# Error Codes
ERROR_INVALID_REQUEST = "INVALID_REQUEST"
ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERROR_PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"
ERROR_DUPLICATE_PAYMENT = "DUPLICATE_PAYMENT"
ERROR_INVALID_AMOUNT = "INVALID_AMOUNT"
ERROR_DATABASE_ERROR = "DATABASE_ERROR"
ERROR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

# General
DEFAULT_CHARSET = "utf-8"
