# Service Constants

# Error Codes
ERROR_INVALID_REQUEST = "INVALID_REQUEST"
ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERROR_ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
ERROR_ORDER_ALREADY_CANCELLED = "ORDER_ALREADY_CANCELLED"
ERROR_DUPLICATE_PAYMENT = "DUPLICATE_PAYMENT"
ERROR_INVALID_TOTAL = "INVALID_TOTAL"
ERROR_EMPTY_CART = "EMPTY_CART"
ERROR_DATABASE_ERROR = "DATABASE_ERROR"
ERROR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

# General
DEFAULT_CHARSET = "utf-8"
