# Service Constants

# Error Codes
ERROR_INVALID_REQUEST = "INVALID_REQUEST"
ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERROR_PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
ERROR_CART_ITEM_NOT_FOUND = "CART_ITEM_NOT_FOUND"
ERROR_OUT_OF_STOCK = "OUT_OF_STOCK"
ERROR_DATABASE_ERROR = "DATABASE_ERROR"
ERROR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

# General
DEFAULT_CHARSET = "utf-8"
